### ISSUE TITLE
Where do you call the functions??

### ISSUE THREAD

**Issue by PembaTamang** [mitchtabian/FirebaseDirectMessage#2]
How to call the functions written in the index.js at https://codingwithmitch.com/blog/android-firebase-cloud-messages-cloud-function/

and the code seems to have errors as well it is not being deployed.

**Comment by mitchtabian** [comment]
You call it by triggering it with an onWrite event.
```
exports.sendNotification = functions.database.ref('/messages/{userId}/{messageId}').onWrite(event => {
	...
```
So when something is inserted into this node: 
```
/messages/{some_user_id}/{Some_message_id}/
```
it will be triggered.
